server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # 🌍 Next.js landing
    location / {
        proxy_pass http://landing:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 🧠 FastAPI Worker
    location /worker/ {
        rewrite ^/worker(/.*)$ $1 break;
        proxy_pass http://worker:8001;
        proxy_set_header Host $host;
    }

	 # ⚙️ Laravel Core API (PHP-FPM) - БЛОК МАРШРУТИЗАЦИИ /api
	 location /api {
		 # 1. Сначала ищем статические файлы (если они есть).
		 # 2. Если не найдено, перенаправляем во внутренний блок @laravel_api.
		 try_files $uri $uri/ @laravel_api;
	 }

	  location /storage/ {
             alias /var/www/html/src/public/storage/;
             access_log off;
             expires max;
             try_files $uri $uri/ =404;
         }

	 # Именованный location для перенаправления всех запросов на index.php
	 location @laravel_api {
		 # Внутреннее перенаправление: /api/test -> /index.php/test
		 # Флаг 'last' заставляет Nginx перезапустить поиск location с новым URI.
		 rewrite ^/api(/.*)$ /index.php$1 last;
	 }

	 # ⚡️ ОБРАБОТЧИК PHP-FPM - ВНЕШНИЙ БЛОК
	 # Он ловит URI, который начинается с /index.php (перенаправлен из @laravel_api)
	 location ~ ^/index\.php(/|$) {
		 # Разделяет URI: /index.php/test -> SCRIPT_NAME: /index.php, PATH_INFO: /test
		 fastcgi_split_path_info ^(.+\.php)(/.+)$;

		 fastcgi_pass core-api:9000;
		 include fastcgi_params;

		 fastcgi_param SCRIPT_FILENAME /var/www/html/src/public/index.php;

		 # Передаем остаток пути в Laravel
		 fastcgi_param PATH_INFO $fastcgi_path_info;
	 }

}