<?php

use app\Application\Service\Markdown\CommonMarkConverter;
use App\Http\Controllers\Api\DocumentController;
use app\Http\Controllers\Api\RateController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PingController;

Route::get('test', fn() => 'ok');

Route::get('/rates/convert', [RateController::class, 'convert']);

Route::get('/test-md', function (CommonMarkConverter $converter) {
    $markdown = <<<MD
# Invoice #123

## Items
- Apple
- Banana
- Carrot

*Generated by Multility API*
MD;
    return $converter->convert($markdown);
});


Route::prefix('documents')->group(function () {
    // Sync (оставим только для dev)
    Route::post('generate', [DocumentController::class, 'generate'])
        ->name('api.documents.generate');

    // Async HTML / Markdown
    Route::post('generate/async', [DocumentController::class, 'generateAsync'])
        ->name('api.documents.generate.async');

    // Async URL
    Route::post('generate-url/async', [DocumentController::class, 'generateFromUrlAsync'])
        ->name('api.documents.generate.url.async');

    // Job status
    Route::get('jobs/{jobId}', [DocumentController::class, 'status'])
        ->name('api.documents.jobs.status');

    // Streaming
    Route::get('{path}', [DocumentController::class, 'stream'])
        ->where('path', '.*')
        ->name('api.documents.stream');
});


Route::middleware(['auth.apikey'])->group(function () {
    Route::get('/ping', PingController::class);
});
